using System;
using System.Collections.Generic;
using System.Globalization;

namespace DellR730xdFanControlCenter;

public static class LocalizationService
{
    public const string DefaultLanguage = "zh-CN";

    private static readonly Dictionary<string, Dictionary<string, string>> Resources = new(StringComparer.OrdinalIgnoreCase)
    {
        ["zh-CN"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["App.Title"] = "R730XD 智控风扇中心",
            ["App.ProductName"] = "戴尔 R730xd 远程管理风扇控制中心",
            ["App.TrayTip"] = "R730XD 风扇控制中心",
            ["Nav.Overview"] = "总览",
            ["Nav.Control"] = "风扇控制",
            ["Nav.Sensors"] = "传感器",
            ["Nav.Settings"] = "设置",
            ["Hero.AppName"] = "戴尔 R730xd 远程管理风扇控制中心",
            ["Hero.Title"] = "R730XD 智控风扇中心",
            ["Hero.Subtitle"] = "监控管理控制器传感器，控制全部或单个风扇，支持戴尔自动模式与软件恒温策略。",
            ["Hero.Target"] = "当前目标",
            ["State.NotConnected"] = "未连接",
            ["State.Connecting"] = "正在连接",
            ["State.Connected"] = "已连接",
            ["State.ConnectedPolling"] = "已连接，{0} 秒轮询",
            ["State.ConnectedPollingTime"] = "已连接，{0} 秒轮询 · {1}",
            ["State.Disconnected"] = "已断开",
            ["State.WaitingRefresh"] = "等待刷新",
            ["Mode.Idle"] = "待机",
            ["Mode.Manual"] = "手动",
            ["Mode.ManualPercent"] = "手动 {0}%",
            ["Mode.PresetManual"] = "预设：{0}（{1:0}%）",
            ["Mode.DellAuto"] = "戴尔自动",
            ["Mode.SmartAuto"] = "软件自动",
            ["Mode.SmartPercent"] = "软件自动 {0}%",
            ["Overview.MaxCpuTemp"] = "最高处理器温度",
            ["Overview.FromSdrTemp"] = "来自传感器数据记录",
            ["Overview.FanStatus"] = "风扇状态",
            ["Overview.FansCount"] = "{0} 个风扇",
            ["Overview.NoFanRpm"] = "未读取到风扇转速",
            ["Overview.Mode"] = "控制模式",
            ["Overview.AutoPolicyStopped"] = "软件自动策略未运行",
            ["Overview.TempBoard"] = "温度大看板",
            ["Overview.TempBoardHelp"] = "逐项显示管理控制器返回的每一个温度传感器。",
            ["Overview.WaitingPoll"] = "等待轮询",
            ["Overview.LastPoll"] = "最后轮询 {0}",
            ["Overview.LastPollWithDuration"] = "最后轮询 {0} · 耗时 {1:0.0} 秒",
            ["Overview.FanBoard"] = "风扇转速看板",
            ["Overview.PowerHealth"] = "功耗与状态",
            ["Overview.QuickActions"] = "快速操作",
            ["Overview.AllFans"] = "全部风扇",
            ["Overview.RecentLog"] = "最新日志",
            ["Overview.VisualizationBoard"] = "交互式数据可视化",
            ["Overview.VisualizationHelp"] = "总览趋势、单项硬件、按硬件类型和健康状态的交互图表。",
            ["Dashboard.VisualizationLoading"] = "图表加载中",
            ["Dashboard.VisualizationReady"] = "图表已就绪",
            ["Dashboard.VisualizationUpdated"] = "图表已更新 {0}",
            ["Dashboard.VisualizationLoadFailed"] = "图表加载失败：{0}",
            ["Dashboard.Title"] = "R730XD 实时硬件图表",
            ["Dashboard.Subtitle"] = "来自远程管理控制器的温度、风扇、功耗和健康状态，支持悬停、缩放和分类查看。",
            ["Dashboard.ViewAll"] = "全部",
            ["Dashboard.ViewTemperature"] = "温度",
            ["Dashboard.ViewFans"] = "风扇",
            ["Dashboard.ViewPower"] = "性能/电气",
            ["Dashboard.ViewStatus"] = "类型与状态",
            ["Dashboard.AverageFanRpm"] = "平均风扇转速",
            ["Dashboard.HardwareTypes"] = "硬件类型",
            ["Dashboard.LastUpdated"] = "更新时间",
            ["Dashboard.HealthState"] = "健康状态",
            ["Dashboard.PerformancePeak"] = "性能峰值",
            ["Dashboard.ElectricalReadings"] = "电气读数",
            ["Dashboard.WarningCount"] = "异常项",
            ["Dashboard.FanRange"] = "风扇范围",
            ["Dashboard.TemperatureSensors"] = "温度传感器",
            ["Dashboard.TrendTitle"] = "总体趋势",
            ["Dashboard.TrendSubtitle"] = "最高温度、平均风扇转速与处理器使用率历史",
            ["Dashboard.CpuUsage"] = "处理器使用率",
            ["Dashboard.MemoryUsage"] = "内存使用率",
            ["Dashboard.IoUsage"] = "输入输出使用率",
            ["Dashboard.SystemUsage"] = "系统使用率",
            ["Dashboard.CurrentSnapshot"] = "当前快照",
            ["Dashboard.OverallTitle"] = "总体硬件画像",
            ["Dashboard.OverallSubtitle"] = "温度、风扇、负载、健康和传感器覆盖",
            ["Dashboard.TemperatureTitle"] = "单项温度排行",
            ["Dashboard.TemperatureSubtitle"] = "每个温度传感器的当前读数",
            ["Dashboard.FanTitle"] = "单风扇转速",
            ["Dashboard.FanSubtitle"] = "1-6 号风扇当前转速对比",
            ["Dashboard.PowerTitle"] = "性能与电气",
            ["Dashboard.PowerSubtitle"] = "处理器、内存、输入输出、系统使用率，以及功耗、电压和电流",
            ["Dashboard.TypeTitle"] = "按硬件类型与状态",
            ["Dashboard.TypeSubtitle"] = "类型构成和全量传感器树图",
            ["Dashboard.SensorTree"] = "全量传感器树",
            ["Dashboard.StatusByType"] = "按类型状态",
            ["Dashboard.Value"] = "数值",
            ["Dashboard.Status"] = "状态",
            ["Dashboard.Unit"] = "单位",
            ["Dashboard.StatusOk"] = "正常",
            ["Dashboard.StatusWarning"] = "需关注",
            ["Dashboard.TypeTemperature"] = "温度",
            ["Dashboard.TypeFan"] = "风扇",
            ["Dashboard.TypePerformance"] = "性能",
            ["Dashboard.TypePower"] = "功耗",
            ["Dashboard.TypeVoltage"] = "电压",
            ["Dashboard.TypeCurrent"] = "电流",
            ["Dashboard.TypeStatus"] = "状态",
            ["Dashboard.TypeNumeric"] = "其他数值",
            ["Dashboard.TypeOther"] = "其他",
            ["SensorDisplay.CpuUsage"] = "处理器使用率",
            ["SensorDisplay.MemoryUsage"] = "内存使用率",
            ["SensorDisplay.IoUsage"] = "输入输出使用率",
            ["SensorDisplay.SystemUsage"] = "系统使用率",
            ["SensorDisplay.PowerConsumption"] = "功耗",
            ["SensorDisplay.InletTemperature"] = "进风温度",
            ["SensorDisplay.ExhaustTemperature"] = "排风温度",
            ["SensorDisplay.FanRpmIndexed"] = "{0} 号风扇转速",
            ["SensorDisplay.VoltageIndexed"] = "{0} 路电压",
            ["SensorDisplay.CurrentIndexed"] = "{0} 路电流",
            ["SensorDisplay.TemperatureIndexed"] = "{0} 号温度",
            ["SensorDisplay.Intrusion"] = "机箱入侵",
            ["SensorDisplay.FanRedundancy"] = "风扇冗余",
            ["SensorDisplay.PowerOptimized"] = "电源优化状态",
            ["Action.Connect"] = "连接",
            ["Action.RefreshSensors"] = "刷新传感器",
            ["Action.Restore10"] = "还原 10%",
            ["Action.OpenIdrac"] = "打开远程管理网页",
            ["Action.Apply"] = "应用",
            ["Action.StartAuto"] = "启动自动",
            ["Action.Stop"] = "停止",
            ["Action.Refresh"] = "刷新",
            ["Action.Save"] = "保存设置",
            ["Control.Presets"] = "预设模式",
            ["Control.CurrentMode"] = "当前模式：{0}",
            ["Control.PresetRules"] = "预设规则",
            ["Control.AddPreset"] = "添加手动预设",
            ["Control.Default"] = "默认",
            ["Control.Manual10"] = "手动 10%",
            ["Control.Balanced"] = "均衡",
            ["Control.Cooling"] = "散热",
            ["Control.Performance"] = "性能",
            ["Control.DellAuto"] = "戴尔自动",
            ["Control.IndividualFans"] = "单风扇控制",
            ["Control.IndividualWarning"] = "单风扇原始目标字节默认关闭。本机 R730XD 远程管理固件 2.82 实测 0x00 目标会让全部风扇高转，启用前请确认你的固件映射。",
            ["Control.IndividualDisabledWarning"] = "单风扇原始目标字节当前未启用。需要使用单风扇控制时，请先在设置中开启并保存。",
            ["Control.IndividualEnabledWarning"] = "单风扇原始目标字节当前已启用。该能力依赖固件映射，本机 R730XD 远程管理固件 2.82 实测 0x00 目标会让全部风扇高转，请谨慎操作。",
            ["Control.IndividualHelp"] = "启用后会发送戴尔原始目标字节：1-6 号风扇映射为 0x00-0x05。若行为不符合预期，请立即恢复戴尔自动模式。",
            ["Control.Set"] = "设置",
            ["Control.TargetTemp"] = "目标温度",
            ["Control.HighTemp"] = "高温",
            ["Control.EmergencyAuto"] = "紧急自动",
            ["Control.PollSeconds"] = "轮询秒数",
            ["Control.SmartAutoPolicy"] = "软件恒温策略",
            ["Control.SmartAutoHelp"] = "按处理器温度线性调整全部风扇；达到紧急温度时切回戴尔自动模式。",
            ["Control.FanDisplayName"] = "风扇 {0}",
            ["Control.FanSubtitle"] = "第 {0} 路风扇",
            ["Preset.ManualSubtitle"] = "手动 {0:0}%",
            ["Preset.RestoreManualSubtitle"] = "恢复手动 {0:0}%",
            ["Preset.DellAutoSubtitle"] = "固件自动",
            ["Preset.Current"] = "正在运行",
            ["Preset.Apply"] = "切换",
            ["Preset.Save"] = "保存",
            ["Preset.Delete"] = "删除",
            ["Preset.Name"] = "预设名称",
            ["Preset.Description"] = "预设说明",
            ["Preset.Percent"] = "风扇百分比",
            ["Preset.NewNamePlaceholder"] = "例如：夜间静音",
            ["Preset.RestoreManualDetail"] = "回到本机默认手动 10%，适合退出测试或恢复安静基线。",
            ["Preset.BalancedDetail"] = "日常监控推荐，兼顾噪音和温度，适合轻负载运行。",
            ["Preset.CoolingDetail"] = "提高散热余量，适合硬盘较多或处理器温度上升时使用。",
            ["Preset.PerformanceDetail"] = "高转速优先，适合短时间高负载、转码或压力测试。",
            ["Preset.DellAutoDetail"] = "交还给远程管理控制器自动策略，由服务器固件接管风扇。",
            ["Preset.CustomDetail"] = "手动创建的风扇规则，可保存百分比并在软件和托盘中快速切换。",
            ["Preset.RestoreManualBadge"] = "恢复默认",
            ["Preset.ManualBadge"] = "手动风扇",
            ["Preset.DellAutoBadge"] = "固件接管",
            ["Preset.BmcMetric"] = "固件",
            ["Preset.PercentMetric"] = "{0:0}%",
            ["Sensors.Title"] = "管理控制器传感器",
            ["Sensors.Key"] = "传感器",
            ["Sensors.Entity"] = "实体",
            ["Sensors.Value"] = "读数",
            ["Sensors.Unit"] = "单位",
            ["Sensors.Status"] = "状态",
            ["Settings.Connection"] = "远程管理连接",
            ["Settings.UserName"] = "用户名",
            ["Settings.Password"] = "密码",
            ["Settings.RememberPassword"] = "使用 Windows 数据保护保存密码",
            ["Settings.BundledIpmiPath"] = "内置 ipmitool 路径",
            ["Settings.Application"] = "应用设置",
            ["Settings.MinimizeToTray"] = "点击关闭时最小化到托盘",
            ["Settings.EnableIndividualFanTargets"] = "启用单风扇原始目标字节",
            ["Settings.FanCount"] = "风扇数量",
            ["Settings.CommandTimeout"] = "命令超时秒数",
            ["Settings.AutoMinFan"] = "自动策略最小风扇百分比",
            ["Settings.AutoMaxFan"] = "自动策略最大风扇百分比",
            ["Settings.Theme"] = "主题",
            ["Settings.Language"] = "界面语言",
            ["Theme.System"] = "跟随系统",
            ["Theme.Light"] = "浅色",
            ["Theme.Dark"] = "深色",
            ["Status.Loaded"] = "应用已加载，设置就绪。",
            ["Status.FirstRunSettingsRequired"] = "首次使用请先在设置页填写远程管理账号、密码并保存。",
            ["Status.Connecting"] = "正在连接远程管理控制器并启动轮询",
            ["Status.ConnectedPolling"] = "已连接并开始自动轮询",
            ["Status.RefreshingSensors"] = "正在刷新传感器",
            ["Status.SensorsRefreshed"] = "传感器已刷新",
            ["Status.SetAllFans"] = "正在设置全部风扇为 {0}%",
            ["Status.AllFansSet"] = "全部风扇已设置为 {0}%",
            ["Status.SingleFanDisabled"] = "单风扇原始目标字节未启用，请先在设置中开启。",
            ["Status.UnknownFan"] = "无法识别风扇编号。",
            ["Status.FanSet"] = "风扇 {0} 已设置为 {1}%",
            ["Status.RestoringDefault"] = "正在还原手动 {0}% 默认模式",
            ["Status.RestoredDefault"] = "已还原为手动 {0}%",
            ["Status.ResettingDellAuto"] = "正在切回戴尔自动风扇模式",
            ["Status.DellAutoRestored"] = "已切回戴尔自动风扇模式",
            ["Status.AutoStarted"] = "软件自动策略运行中",
            ["Status.AutoStopped"] = "软件自动策略未运行",
            ["Status.OpenedIdrac"] = "已打开远程管理网页：{0}",
            ["Status.SettingsSaved"] = "设置已保存",
            ["Status.PresetApplied"] = "已切换到预设：{0}",
            ["Status.PresetSaved"] = "预设规则已保存：{0}",
            ["Status.PresetAdded"] = "已添加手动预设：{0}",
            ["Status.PresetDeleted"] = "已删除预设：{0}",
            ["Status.LanguageChanged"] = "界面语言已切换为 {0}",
            ["Status.PollingStarted"] = "传感器轮询已启动，间隔 {0} 秒。",
            ["Status.PollingStopped"] = "传感器轮询已停止：{0}",
            ["Status.PollingLatencyExceeded"] = "本次传感器轮询耗时 {0:0.0} 秒，超过当前 {1:0.0} 秒间隔。建议把轮询间隔设为 {2} 秒或以上；1 秒只是发起频率，不是实时流式返回。",
            ["Status.PollingSkippedPreviousRunning"] = "上一轮传感器轮询尚未完成，本次周期已跳过。当前间隔 {0} 秒，最近完整轮询耗时 {1:0.0} 秒，建议设置为 {2} 秒或以上。",
            ["Status.PollingSkippedPreviousRunningNoSample"] = "上一轮传感器轮询尚未完成，本次周期已跳过。当前间隔 {0} 秒；等待第一轮完整耗时后会给出建议间隔。",
            ["Status.PollingSkippedIpmiBusy"] = "带外管理命令正在执行，本次传感器轮询已跳过。当前间隔 {0} 秒，最近完整轮询耗时 {1:0.0} 秒，建议设置为 {2} 秒或以上。",
            ["Status.PollingSkippedIpmiBusyNoSample"] = "带外管理命令正在执行，本次传感器轮询已跳过。当前间隔 {0} 秒；等待第一轮完整耗时后会给出建议间隔。",
            ["Status.PollingRecovered"] = "传感器轮询恢复正常，本次耗时 {0:0.0} 秒。",
            ["Status.AutoTickSkipped"] = "上一次自动策略仍在运行，已跳过本次周期。",
            ["Status.EmergencyAuto"] = "处理器 {0:0.0} °C 达到紧急阈值，已恢复戴尔自动模式。",
            ["Status.SmartFanApplied"] = "处理器 {0:0.0} °C -> 全部风扇 {1}%。",
            ["Status.CommandStarted"] = "开始执行：{0}",
            ["Log.Info"] = "信息",
            ["Log.Warn"] = "警告",
            ["Log.Error"] = "错误",
            ["Log.Ok"] = "成功",
            ["Log.Fail"] = "失败",
            ["Validation.Empty"] = "{0} 不能为空。",
            ["Validation.AutoFanRange"] = "自动策略最小风扇百分比必须小于或等于最大风扇百分比。",
            ["Validation.TemperatureOrder"] = "温度阈值必须按目标温度 < 高温 < 紧急自动排序。",
            ["Validation.PresetNameRequired"] = "预设名称不能为空。",
            ["Validation.PresetNotFound"] = "无法找到预设规则：{0}",
            ["Validation.CannotDeleteBuiltInPreset"] = "内置预设不能删除。",
            ["Field.FanCount"] = "风扇数量",
            ["Field.CommandTimeout"] = "命令超时秒数",
            ["Field.SensorRefreshSeconds"] = "轮询秒数",
            ["Field.TargetTemperature"] = "目标温度",
            ["Field.HighTemperature"] = "高温",
            ["Field.EmergencyTemperature"] = "紧急自动温度",
            ["Field.AutoMinimumFanPercent"] = "自动策略最小风扇百分比",
            ["Field.AutoMaximumFanPercent"] = "自动策略最大风扇百分比",
            ["Field.AllFanPercent"] = "全部风扇百分比",
            ["Field.DefaultAllFanPercent"] = "默认全部风扇百分比",
            ["Field.SingleFanPercent"] = "风扇 {0} 百分比",
            ["Tray.Restore"] = "打开主窗口",
            ["Tray.FanControlGroup"] = "风扇控制",
            ["Tray.Presets"] = "预设模式",
            ["Tray.AllFanSpeeds"] = "全部风扇转速",
            ["Tray.AllFans20"] = "全部风扇 20%",
            ["Tray.AllFans35"] = "全部风扇 35%",
            ["Tray.AllFans50"] = "全部风扇 50%",
            ["Tray.RestoreDefault"] = "还原手动 10%",
            ["Tray.Settings"] = "设置",
            ["Tray.Exit"] = "退出",
            ["Tray.BalloonTitle"] = "R730XD 智控风扇中心",
            ["Tray.BalloonMessage"] = "软件仍在后台运行，可右击托盘图标快速控制风扇。",
        },
        ["en-US"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["App.Title"] = "R730XD Smart Fan Center",
            ["App.ProductName"] = "Dell R730xd iDRAC Fan Control Center",
            ["App.TrayTip"] = "R730XD Fan Control Center",
            ["Nav.Overview"] = "Overview",
            ["Nav.Control"] = "Fan Control",
            ["Nav.Sensors"] = "Sensors",
            ["Nav.Settings"] = "Settings",
            ["Hero.AppName"] = "Dell R730xd iDRAC Fan Control Center",
            ["Hero.Title"] = "R730XD Smart Fan Center",
            ["Hero.Subtitle"] = "Monitor BMC sensors, control all or individual fans, and use Dell auto mode or smart temperature automation.",
            ["Hero.Target"] = "Current target",
            ["State.NotConnected"] = "Not connected",
            ["State.Connecting"] = "Connecting",
            ["State.Connected"] = "Connected",
            ["State.ConnectedPolling"] = "Connected, {0}s polling",
            ["State.ConnectedPollingTime"] = "Connected, {0}s polling · {1}",
            ["State.Disconnected"] = "Disconnected",
            ["State.WaitingRefresh"] = "Waiting for refresh",
            ["Mode.Idle"] = "Idle",
            ["Mode.Manual"] = "Manual",
            ["Mode.ManualPercent"] = "Manual {0}%",
            ["Mode.PresetManual"] = "Preset: {0} ({1:0}%)",
            ["Mode.DellAuto"] = "Dell Auto",
            ["Mode.SmartAuto"] = "Smart Auto",
            ["Mode.SmartPercent"] = "Smart {0}%",
            ["Overview.MaxCpuTemp"] = "Max CPU temperature",
            ["Overview.FromSdrTemp"] = "From SDR temperature sensors",
            ["Overview.FanStatus"] = "Fan status",
            ["Overview.FansCount"] = "{0} fans",
            ["Overview.NoFanRpm"] = "No fan RPM readings",
            ["Overview.Mode"] = "Control mode",
            ["Overview.AutoPolicyStopped"] = "Smart auto policy stopped",
            ["Overview.TempBoard"] = "Temperature Board",
            ["Overview.TempBoardHelp"] = "Shows every temperature sensor reported by BMC SDR.",
            ["Overview.WaitingPoll"] = "Waiting for polling",
            ["Overview.LastPoll"] = "Last poll {0}",
            ["Overview.LastPollWithDuration"] = "Last poll {0} · {1:0.0}s",
            ["Overview.FanBoard"] = "Fan RPM Board",
            ["Overview.PowerHealth"] = "Power & Health",
            ["Overview.QuickActions"] = "Quick Actions",
            ["Overview.AllFans"] = "All Fans",
            ["Overview.RecentLog"] = "Recent Log",
            ["Overview.VisualizationBoard"] = "Interactive Data Visualization",
            ["Overview.VisualizationHelp"] = "Interactive charts for overall trends, individual hardware items, hardware types, and health state.",
            ["Dashboard.VisualizationLoading"] = "Loading charts",
            ["Dashboard.VisualizationReady"] = "Charts ready",
            ["Dashboard.VisualizationUpdated"] = "Charts updated {0}",
            ["Dashboard.VisualizationLoadFailed"] = "Chart load failed: {0}",
            ["Dashboard.Title"] = "R730XD Live Hardware Charts",
            ["Dashboard.Subtitle"] = "Temperature, fan, power, and health data from iDRAC/BMC SDR with hover, zoom, and type views.",
            ["Dashboard.ViewAll"] = "All",
            ["Dashboard.ViewTemperature"] = "Temperature",
            ["Dashboard.ViewFans"] = "Fans",
            ["Dashboard.ViewPower"] = "Performance / electrical",
            ["Dashboard.ViewStatus"] = "Types & health",
            ["Dashboard.AverageFanRpm"] = "Average fan RPM",
            ["Dashboard.HardwareTypes"] = "Hardware types",
            ["Dashboard.LastUpdated"] = "Updated",
            ["Dashboard.HealthState"] = "Health state",
            ["Dashboard.PerformancePeak"] = "Performance peak",
            ["Dashboard.ElectricalReadings"] = "Electrical readings",
            ["Dashboard.WarningCount"] = "Attention items",
            ["Dashboard.FanRange"] = "Fan range",
            ["Dashboard.TemperatureSensors"] = "Temperature sensors",
            ["Dashboard.TrendTitle"] = "Overall Trends",
            ["Dashboard.TrendSubtitle"] = "Max temperature, average fan RPM, and CPU usage history",
            ["Dashboard.CpuUsage"] = "CPU usage",
            ["Dashboard.MemoryUsage"] = "Memory usage",
            ["Dashboard.IoUsage"] = "I/O usage",
            ["Dashboard.SystemUsage"] = "System usage",
            ["Dashboard.CurrentSnapshot"] = "Current snapshot",
            ["Dashboard.OverallTitle"] = "Overall Hardware Profile",
            ["Dashboard.OverallSubtitle"] = "Temperature, fans, load, health, and sensor coverage",
            ["Dashboard.TemperatureTitle"] = "Individual Temperature Ranking",
            ["Dashboard.TemperatureSubtitle"] = "Current value for every temperature sensor",
            ["Dashboard.FanTitle"] = "Individual Fan RPM",
            ["Dashboard.FanSubtitle"] = "Current Fan 1-6 speed comparison",
            ["Dashboard.PowerTitle"] = "Performance & Electrical",
            ["Dashboard.PowerSubtitle"] = "CPU/IO/MEM/SYS usage, power, voltage, and current",
            ["Dashboard.TypeTitle"] = "By Hardware Type & State",
            ["Dashboard.TypeSubtitle"] = "Type composition and full sensor treemap",
            ["Dashboard.SensorTree"] = "Full sensor tree",
            ["Dashboard.StatusByType"] = "State by type",
            ["Dashboard.Value"] = "Value",
            ["Dashboard.Status"] = "Status",
            ["Dashboard.Unit"] = "Unit",
            ["Dashboard.StatusOk"] = "OK",
            ["Dashboard.StatusWarning"] = "Attention",
            ["Dashboard.TypeTemperature"] = "Temperature",
            ["Dashboard.TypeFan"] = "Fans",
            ["Dashboard.TypePerformance"] = "Performance",
            ["Dashboard.TypePower"] = "Power",
            ["Dashboard.TypeVoltage"] = "Voltage",
            ["Dashboard.TypeCurrent"] = "Current",
            ["Dashboard.TypeStatus"] = "Status",
            ["Dashboard.TypeNumeric"] = "Other numeric",
            ["Dashboard.TypeOther"] = "Other",
            ["SensorDisplay.CpuUsage"] = "CPU usage",
            ["SensorDisplay.MemoryUsage"] = "Memory usage",
            ["SensorDisplay.IoUsage"] = "I/O usage",
            ["SensorDisplay.SystemUsage"] = "System usage",
            ["SensorDisplay.PowerConsumption"] = "Power consumption",
            ["SensorDisplay.InletTemperature"] = "Inlet temperature",
            ["SensorDisplay.ExhaustTemperature"] = "Exhaust temperature",
            ["SensorDisplay.FanRpmIndexed"] = "Fan {0} RPM",
            ["SensorDisplay.VoltageIndexed"] = "Voltage {0}",
            ["SensorDisplay.CurrentIndexed"] = "Current {0}",
            ["SensorDisplay.TemperatureIndexed"] = "Temperature {0}",
            ["SensorDisplay.Intrusion"] = "Chassis intrusion",
            ["SensorDisplay.FanRedundancy"] = "Fan redundancy",
            ["SensorDisplay.PowerOptimized"] = "Power optimized",
            ["Action.Connect"] = "Connect",
            ["Action.RefreshSensors"] = "Refresh sensors",
            ["Action.Restore10"] = "Restore 10%",
            ["Action.OpenIdrac"] = "Open iDRAC",
            ["Action.Apply"] = "Apply",
            ["Action.StartAuto"] = "Start auto",
            ["Action.Stop"] = "Stop",
            ["Action.Refresh"] = "Refresh",
            ["Action.Save"] = "Save settings",
            ["Control.Presets"] = "Presets",
            ["Control.CurrentMode"] = "Current mode: {0}",
            ["Control.PresetRules"] = "Preset rules",
            ["Control.AddPreset"] = "Add manual preset",
            ["Control.Default"] = "Default",
            ["Control.Manual10"] = "Manual 10%",
            ["Control.Balanced"] = "Balanced",
            ["Control.Cooling"] = "Cooling",
            ["Control.Performance"] = "Performance",
            ["Control.DellAuto"] = "Dell Auto",
            ["Control.IndividualFans"] = "Individual Fans",
            ["Control.IndividualWarning"] = "Individual raw targets are disabled by default. On the local R730XD/iDRAC 2.82, target 0x00 ramped all fans high; verify your firmware mapping before enabling.",
            ["Control.IndividualDisabledWarning"] = "Individual raw targets are currently not enabled. Turn them on and save in Settings before using individual fan control.",
            ["Control.IndividualEnabledWarning"] = "Individual raw targets are currently enabled. This depends on firmware mapping; on the local R730XD/iDRAC 2.82, target 0x00 ramped all fans high. Use with care.",
            ["Control.IndividualHelp"] = "When enabled, Dell OEM raw target bytes map Fan 1-6 to 0x00-0x05. If behavior is unexpected, restore Dell auto mode immediately.",
            ["Control.Set"] = "Set",
            ["Control.TargetTemp"] = "Target temperature",
            ["Control.HighTemp"] = "High temperature",
            ["Control.EmergencyAuto"] = "Emergency auto",
            ["Control.PollSeconds"] = "Polling seconds",
            ["Control.SmartAutoPolicy"] = "Smart Auto Policy",
            ["Control.SmartAutoHelp"] = "Linearly adjusts all fans by CPU temperature; switches to Dell auto mode at the emergency threshold.",
            ["Control.FanDisplayName"] = "Fan {0}",
            ["Control.FanSubtitle"] = "Channel {0}",
            ["Preset.ManualSubtitle"] = "Manual {0:0}%",
            ["Preset.RestoreManualSubtitle"] = "Restore manual {0:0}%",
            ["Preset.DellAutoSubtitle"] = "BMC auto",
            ["Preset.Current"] = "Running",
            ["Preset.Apply"] = "Switch",
            ["Preset.Save"] = "Save",
            ["Preset.Delete"] = "Delete",
            ["Preset.Name"] = "Preset name",
            ["Preset.Description"] = "Preset description",
            ["Preset.Percent"] = "Fan percent",
            ["Preset.NewNamePlaceholder"] = "Example: Night quiet",
            ["Preset.RestoreManualDetail"] = "Return to the local default manual 10% baseline for ending tests or quiet recovery.",
            ["Preset.BalancedDetail"] = "Recommended daily profile that balances noise and temperature for light workloads.",
            ["Preset.CoolingDetail"] = "Adds cooling headroom for dense drives or rising CPU temperature.",
            ["Preset.PerformanceDetail"] = "Prioritizes airflow for short high-load, transcoding, or stress-test sessions.",
            ["Preset.DellAutoDetail"] = "Hands fan control back to the iDRAC/BMC firmware policy.",
            ["Preset.CustomDetail"] = "User-created fan rule. Save the percent and switch it from the app or tray menu.",
            ["Preset.RestoreManualBadge"] = "Restore default",
            ["Preset.ManualBadge"] = "Manual fans",
            ["Preset.DellAutoBadge"] = "Firmware managed",
            ["Preset.BmcMetric"] = "BMC",
            ["Preset.PercentMetric"] = "{0:0}%",
            ["Sensors.Title"] = "BMC Sensors",
            ["Sensors.Key"] = "Sensor",
            ["Sensors.Entity"] = "Entity",
            ["Sensors.Value"] = "Value",
            ["Sensors.Unit"] = "Unit",
            ["Sensors.Status"] = "Status",
            ["Settings.Connection"] = "iDRAC Connection",
            ["Settings.UserName"] = "Username",
            ["Settings.Password"] = "Password",
            ["Settings.RememberPassword"] = "Remember password with DPAPI",
            ["Settings.BundledIpmiPath"] = "Bundled ipmitool path",
            ["Settings.Application"] = "Application",
            ["Settings.MinimizeToTray"] = "Minimize to tray on close",
            ["Settings.EnableIndividualFanTargets"] = "Enable individual fan raw targets",
            ["Settings.FanCount"] = "Fan count",
            ["Settings.CommandTimeout"] = "Command timeout seconds",
            ["Settings.AutoMinFan"] = "Auto policy minimum fan percent",
            ["Settings.AutoMaxFan"] = "Auto policy maximum fan percent",
            ["Settings.Theme"] = "Theme",
            ["Settings.Language"] = "Interface language",
            ["Theme.System"] = "System",
            ["Theme.Light"] = "Light",
            ["Theme.Dark"] = "Dark",
            ["Status.Loaded"] = "Application loaded. Settings are ready.",
            ["Status.FirstRunSettingsRequired"] = "First-time use: enter and save iDRAC account and password on the Settings page.",
            ["Status.Connecting"] = "Connecting to iDRAC and starting polling",
            ["Status.ConnectedPolling"] = "Connected and polling",
            ["Status.RefreshingSensors"] = "Refreshing sensors",
            ["Status.SensorsRefreshed"] = "Sensors refreshed",
            ["Status.SetAllFans"] = "Setting all fans to {0}%",
            ["Status.AllFansSet"] = "All fans set to {0}%",
            ["Status.SingleFanDisabled"] = "Individual raw targets are not enabled. Turn them on in Settings first.",
            ["Status.UnknownFan"] = "Unable to identify the fan index.",
            ["Status.FanSet"] = "Fan {0} set to {1}%",
            ["Status.RestoringDefault"] = "Restoring manual {0}% default",
            ["Status.RestoredDefault"] = "Restored manual {0}%",
            ["Status.ResettingDellAuto"] = "Resetting Dell automatic fan mode",
            ["Status.DellAutoRestored"] = "Dell automatic fan mode restored",
            ["Status.AutoStarted"] = "Smart auto policy running",
            ["Status.AutoStopped"] = "Smart auto policy stopped",
            ["Status.OpenedIdrac"] = "Opened iDRAC web console: {0}",
            ["Status.SettingsSaved"] = "Settings saved",
            ["Status.PresetApplied"] = "Switched to preset: {0}",
            ["Status.PresetSaved"] = "Preset rule saved: {0}",
            ["Status.PresetAdded"] = "Manual preset added: {0}",
            ["Status.PresetDeleted"] = "Preset deleted: {0}",
            ["Status.LanguageChanged"] = "Interface language changed to {0}",
            ["Status.PollingStarted"] = "Sensor polling started at {0}s interval.",
            ["Status.PollingStopped"] = "Sensor polling stopped: {0}",
            ["Status.PollingLatencyExceeded"] = "This SDR poll took {0:0.0}s, exceeding the configured {1:0.0}s interval. Recommended polling interval: {2}s or higher; 1s is only the request cadence, not real-time streaming.",
            ["Status.PollingSkippedPreviousRunning"] = "The previous SDR poll is still running; this tick was skipped. Current interval is {0}s, last complete poll took {1:0.0}s, recommended interval is {2}s or higher.",
            ["Status.PollingSkippedPreviousRunningNoSample"] = "The previous SDR poll is still running; this tick was skipped. Current interval is {0}s; a recommendation will be shown after the first complete timing sample.",
            ["Status.PollingSkippedIpmiBusy"] = "An IPMI command is running; this sensor poll was skipped. Current interval is {0}s, last complete poll took {1:0.0}s, recommended interval is {2}s or higher.",
            ["Status.PollingSkippedIpmiBusyNoSample"] = "An IPMI command is running; this sensor poll was skipped. Current interval is {0}s; a recommendation will be shown after the first complete timing sample.",
            ["Status.PollingRecovered"] = "Sensor polling recovered. This poll took {0:0.0}s.",
            ["Status.AutoTickSkipped"] = "Skipped auto policy tick because the previous tick is still running.",
            ["Status.EmergencyAuto"] = "CPU {0:0.0} °C reached emergency threshold; Dell auto mode restored.",
            ["Status.SmartFanApplied"] = "CPU {0:0.0} °C -> all fans {1}%.",
            ["Status.CommandStarted"] = "Started: {0}",
            ["Log.Info"] = "Info",
            ["Log.Warn"] = "Warn",
            ["Log.Error"] = "Error",
            ["Log.Ok"] = "OK",
            ["Log.Fail"] = "Fail",
            ["Validation.Empty"] = "{0} is empty.",
            ["Validation.AutoFanRange"] = "Auto minimum fan percent must be less than or equal to auto maximum fan percent.",
            ["Validation.TemperatureOrder"] = "Temperature thresholds must be ordered as Target < High < Emergency.",
            ["Validation.PresetNameRequired"] = "Preset name is required.",
            ["Validation.PresetNotFound"] = "Unable to find preset rule: {0}",
            ["Validation.CannotDeleteBuiltInPreset"] = "Built-in presets cannot be deleted.",
            ["Field.FanCount"] = "Fan count",
            ["Field.CommandTimeout"] = "Command timeout",
            ["Field.SensorRefreshSeconds"] = "Sensor refresh seconds",
            ["Field.TargetTemperature"] = "Target temperature",
            ["Field.HighTemperature"] = "High temperature",
            ["Field.EmergencyTemperature"] = "Emergency temperature",
            ["Field.AutoMinimumFanPercent"] = "Auto minimum fan percent",
            ["Field.AutoMaximumFanPercent"] = "Auto maximum fan percent",
            ["Field.AllFanPercent"] = "All fan percent",
            ["Field.DefaultAllFanPercent"] = "Default all fan percent",
            ["Field.SingleFanPercent"] = "Fan {0} percent",
            ["Tray.Restore"] = "Restore window",
            ["Tray.FanControlGroup"] = "Fan Control",
            ["Tray.Presets"] = "Presets",
            ["Tray.AllFanSpeeds"] = "All fan speeds",
            ["Tray.AllFans20"] = "All fans 20%",
            ["Tray.AllFans35"] = "All fans 35%",
            ["Tray.AllFans50"] = "All fans 50%",
            ["Tray.RestoreDefault"] = "Restore manual 10%",
            ["Tray.Settings"] = "Settings",
            ["Tray.Exit"] = "Exit",
            ["Tray.BalloonTitle"] = "R730XD Smart Fan Center",
            ["Tray.BalloonMessage"] = "The app is still running in the background. Right-click the tray icon for quick fan controls.",
        },
    };

    public static IReadOnlyList<LanguageOption> SupportedLanguages { get; } =
    [
        new LanguageOption { Code = "zh-CN", DisplayName = "简体中文" },
        new LanguageOption { Code = "en-US", DisplayName = "English" },
    ];

    public static string CurrentLanguage { get; private set; } = DefaultLanguage;

    public static bool IsSupportedLanguage(string language)
    {
        return Resources.ContainsKey(language);
    }

    public static void SetLanguage(string language)
    {
        if (!Resources.ContainsKey(language))
        {
            throw new InvalidOperationException($"Unsupported UI language: {language}");
        }

        CurrentLanguage = language;
    }

    public static string T(string key)
    {
        return T(key, CurrentLanguage);
    }

    public static string T(string key, string language)
    {
        if (!Resources.ContainsKey(language))
        {
            throw new InvalidOperationException($"Unsupported UI language: {language}");
        }

        if (Resources[language].TryGetValue(key, out var value))
        {
            return value;
        }

        throw new InvalidOperationException($"Missing UI translation: {language}/{key}");
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(CultureInfo.GetCultureInfo(CurrentLanguage), T(key), args);
    }
}
